---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  interval: 30m
  chart:
    spec:
      chart: policy-reporter
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
      interval: 12h
  values:
    monitoring:
      enabled: true
    metrics:
      enabled: false
