apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - infrastructure/ingress-nginx.yaml
  - infrastructure/kyverno.yaml
  - infrastructure/weave-gitops.yaml
