apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - apps/ping-me.yaml
  - infrastructure/ingress-nginx.yaml
  - infrastructure/kube-prometheus-stack.yaml
  - infrastructure/kyverno.yaml
  - infrastructure/policy-reporter.yaml
  - infrastructure/weave-gitops.yaml
